- hosts: linux
  vars:
    training:
      topic: ansible
      trainer: satish
      labs: aws
  tasks:
  - name: print dict variable
    debug:
      msg: "{{ training['topic'] }}"
  - name: print another way
    debug:
      msg: "key is {{ item.key }} and value is {{ item.value }}"
    with_dict: "{{ training }}"
